when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration



zenstruck_foundry:
    auto_refresh_proxies: true
    faker:
        locale: 'fr_FR'
        seed: 1234
    orm:
        auto_persist: true
        reset: true

